[package]
name = "raig"
version = "0.1.1"
authors = ["Modi Goldstein-Rosenfeld <mbg237@cornell.edu>", "Adrian Sampson <asampson@cs.cornell.edu>", "Kevin Laeufer <laeufer@cornell.edu>"]
edition = "2024"
rust-version = "1.85"
description = "A library for boolean logic verification using And-Inverter Graphs (AIGs)"
documentation = "https://docs.rs/raig"
repository = "https://github.com/cucapra/raig"
license = "MIT"
keywords = ["aig", "aiger", "logic", "verification", "boolean"]
categories = ["data-structures", "development-tools::testing", "parsing", "simulation"]
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/src/**",
]

[workspace]
members = ["crates/raig-cli"]

[dependencies]

[dev-dependencies]
mutaig = "0.4.2"
aig = "0.4.6"
