[package]
name = "raig-memory-benchmarks"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
raig = { path = "../.." }
mutaig = "0.4.2"
aig = "0.4.6"

[[bin]]
name = "memory_raig"
path = "memory_raig.rs"

[[bin]]
name = "memory_mutaig"
path = "memory_mutaig.rs"

[[bin]]
name = "memory_aig_rs"
path = "memory_aig_rs.rs"
